name: Python Application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9.6  # Ensure you're using Python 3.9.6
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.6'  # Specify Python 3.9.6 explicitly

    - name: Install distutils if necessary  # For Python 3.9, distutils should already be included, but just in case
      run: sudo apt-get install python3-distutils

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run your Python script
      run: python run_chsh_inequality.py
