name: Python Application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Assuming you're using Python 3.12

    - name: Install distutils for Python
      run: sudo apt-get install python3-distutils

    # Alternatively, you can use pip to install distutils as part of setuptools and wheel
    # - name: Install setuptools and wheel
    #   run: pip install --upgrade setuptools wheel

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run your Python script
      run: python run_chsh_inequality.py
